[project]
name = "learning-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.10.17",
    "dbt-databricks>=1.11.0",
    "ignr>=2.2",
    "python-dotenv>=1.2.1",
]
